@echo.
@echo [This script is generated by VSHADOW.EXE for the shadow set {1d6867ac-31bf-4b8e-83ce-54cbff67a59c}]
@echo.

SET SHADOW_SET_ID={1d6867ac-31bf-4b8e-83ce-54cbff67a59c}
SET SHADOW_ID_1={e194142e-b970-4096-8d67-7067292128a1}
SET SHADOW_DEVICE_1=\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy12
