<?php

$dbList = array (
	'beirc.co.uk'                => '/home/kim/dev/src/www/yii/beirc.co.uk | /home/beirc.co.uk/dev/src/www/yii/beirc.co.uk',
	'dumfriesfurniture.com'      => '/home/kim/dev/src/www/yii/dumfriesfurniture.com | /home/dumfriesfurniture.com/dev/src/www/yii/dumfriesfurniture.com',
	//'glitzaratti.com'            => '/home/kim/dev/src/www/yii/glitzaratti.com | /home/glitzaratti.com/dev/src/www/yii/glitzaratti.com',
	'jacquiesbeauty.co.uk'       => '/home/kim/dev/src/www/yii/jacquiesbeauty.co.uk | /home/jacquiesbeauty.co.uk/dev/src/www/yii/jacquiesbeauty.co.uk',
	'styleyourvenue.co.uk'       => '/home/kim/dev/src/www/yii/styleyourvenue.co.uk | /home/wireflydesign.com/domains/style.wireflydesign.com/dev/src/www/yii/styleyourvenue.co.uk',
	'test.wireflydesign.com'     => '/home/kim/dev/src/www/yii/test.wireflydesign.com | /home/wireflydesign.com/domains/test.wireflydesign.com/dev/src/www/yii/test.wireflydesign.com',
	'the-art-room.co.uk'         => '/home/kim/dev/src/www/yii/the-art-room.co.uk | /home/the-art-room.co.uk/dev/src/www/yii/the-art-room.co.uk',
);

?>
